version: "3.8"

services:
  bot:
    image: ghcr.io/antarespadas/al-azif-bot:latest
    container_name: al-azif-bot
    restart: unless-stopped
    environment:
      - AlAzif:Token=your_token_here
    volumes:
      - ./AlAzif.Bot/appsettings.json:/app/appsettings.json
    # Run the bot in the same network as Lavalink
    network_mode: service:lavalink
  lavalink:
    # pin the image version to Lavalink v4
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: al-azif-lavalink
    restart: unless-stopped
    environment:
      # set Java options here
      - _JAVA_OPTIONS=-Xmx6G
    volumes:
      # mount application.yml from the same directory or use environment variables
      - ./lavalink.yml:/opt/Lavalink/application.yml
      # persist plugins between restarts, make sure to set the correct permissions (user: 322, group: 322)
      - ./plugins/:/opt/Lavalink/plugins/
    expose:
      - 2333